# -*- coding: utf-8 -*-
"""Copy of image_processing_proj3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrfsSyqZ5lzW3GvS2JciwqMKIHqdK-Hw
"""

import torch
import torchvision.transforms as transforms
from torchvision.models import mobilenet_v3_large, MobileNet_V3_Large_Weights
from PIL import Image
import requests
from io import BytesIO
import matplotlib.pyplot as plt
import torch
import torchvision.transforms as transforms
from torchvision.models import mobilenet_v3_large, MobileNet_V3_Large_Weights
from PIL import Image
import matplotlib.pyplot as plt
import os


def get_device():
    """Prefer MPS (Apple Silicon GPU), then CUDA, then CPU."""
    if getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
        return torch.device("mps")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


# 1. Load Pretrained MobileNet V3 with the latest weights API
weights = MobileNet_V3_Large_Weights.DEFAULT
model = mobilenet_v3_large(weights=weights)
model.eval()

"""# Part 2"""


# from roboflow import Roboflow
# rf = Roboflow(api_key="zcApQr54bnD6POqEKFmP")
# project = rf.workspace("maya-mlots").project("dog-nmpmi-f1sao")
# version = project.version(1)
# dataset = version.download("voc")

from roboflow import Roboflow
rf = Roboflow(api_key="zcApQr54bnD6POqEKFmP")
project = rf.workspace("maya-mlots").project("dog-nmpmi-f1sao")
version = project.version(2)
dataset = version.download("voc")


print(f"\nTotal images in dataset: {version.images}")

import os
import xml.etree.ElementTree as ET
import pandas as pd

def get_dimensions_df(root_path):
    data = []
    # VOC dataset typically uses these three splits
    splits = ['train', 'valid', 'test']

    for split in splits:
        split_path = os.path.join(root_path, split)
        if not os.path.exists(split_path):
            continue

        # List all XML files in the folder
        xml_files = [f for f in os.listdir(split_path) if f.endswith('.xml')]

        for f in xml_files:
            xml_p = os.path.join(split_path, f)
            tree = ET.parse(xml_p)
            root = tree.getroot()

            # Extract width and height from the <size> tag
            size = root.find('size')
            if size is not None:
                w = int(size.find('width').text)
                h = int(size.find('height').text)

                data.append({
                    'split': split,
                    'filename': f.replace('.xml', '.jpg'),
                    'width': w,
                    'height': h
                })

    return pd.DataFrame(data)

# 1. Generate the DataFrame
dataset_path = './dog-2' # Ensure this matches your folder
df_dims = get_dimensions_df(dataset_path)

# 2. Print basic info and statistics
print(f"Processed {len(df_dims)} XML files.")
print("\n--- Summary Statistics ---")
print(df_dims[['width', 'height']].describe().loc[['min', 'max', 'mean']])

# 3. Export to CSV for your Masters Project files
df_dims.to_csv('dataset_dimensions_report.csv', index=False)
print("\nResults saved to 'dataset_dimensions_report.csv'.")

# Display the first few rows
df_dims.head()

def get_full_dataset_df(root_path):
    data = []
    splits = ['train', 'valid', 'test']

    for split in splits:
        split_path = os.path.join(root_path, split)
        if not os.path.exists(split_path): continue

        xml_files = [f for f in os.listdir(split_path) if f.endswith('.xml')]

        for f in xml_files:
            tree = ET.parse(os.path.join(split_path, f))
            root = tree.getroot()

            w = int(root.find('size').find('width').text)
            h = int(root.find('size').find('height').text)

            # Loop through every object in the image
            for obj in root.findall('object'):
                label = obj.find('name').text
                box = obj.find('bndbox')

                data.append({
                    'split': split,
                    'filename': f.replace('.xml', '.jpg'),
                    'width': w,
                    'height': h,
                    'class': label,
                    'xmin': int(box.find('xmin').text),
                    'ymin': int(box.find('ymin').text),
                    'xmax': int(box.find('xmax').text),
                    'ymax': int(box.find('ymax').text)
                })
    return pd.DataFrame(data)

df_full = get_full_dataset_df(dataset_path)

import cv2
import matplotlib.pyplot as plt
import random

def visualize_from_df(df, root_path, num_samples=8):
    plt.figure(figsize=(20, 10))
    # Get unique filenames to ensure we don't pick the same image twice
    unique_files = df['filename'].unique()
    sample_files = random.sample(list(unique_files), min(num_samples, len(unique_files)))

    for i, filename in enumerate(sample_files):
        # Get metadata for this image
        img_info = df[df['filename'] == filename].iloc[0]
        img_path = os.path.join(root_path, img_info['split'], filename)

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Draw all boxes associated with this filename
        boxes = df[df['filename'] == filename]
        for _, box in boxes.iterrows():
            cv2.rectangle(image, (box['xmin'], box['ymin']),
                          (box['xmax'], box['ymax']), (0, 255, 0), 3)
            cv2.putText(image, box['class'], (box['xmin'], box['ymin']-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

        plt.subplot(2, 4, i + 1)
        plt.imshow(image)
        plt.title(f"{filename}\n{img_info['width']}x{img_info['height']}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()

visualize_from_df(df_full, dataset_path)

# Commented out IPython magic to ensure Python compatibility.

# Cell 2: Launch TensorBoard pointing to your Drive folder
# %load_ext tensorboard
# %tensorboard --logdir ./runs

# %load_ext tensorboard
# %tensorboard --logdir runs

import os
import cv2
import torch
import torch.nn as nn
import numpy as np
import xml.etree.ElementTree as ET
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from torchvision import transforms, models
import torchvision.transforms.functional as TF
import torchvision.utils as vutils

# --- 1. Custom Dataset Class ---
class Part2Dataset(Dataset):
    def __init__(self, root_dir, split='train', transform=None, augment=False):
        self.root = os.path.join(root_dir, split)
        if not os.path.exists(self.root):
            raise FileNotFoundError(f"Directory not found: {self.root}")
        self.img_files = sorted([f for f in os.listdir(self.root) if f.endswith('.jpg')])
        self.transform = transform
        self.augment = augment

    def __len__(self):
        return len(self.img_files)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root, self.img_files[idx])
        xml_path = img_path.replace('.jpg', '.xml')

        image = Image.open(img_path).convert("RGB")
        w, h = image.size

        tree = ET.parse(xml_path)
        root = tree.getroot()
        box = root.find('object').find('bndbox')

        # Normalized coordinates (0 to 1)
        xmin = float(box.find('xmin').text) / w
        ymin = float(box.find('ymin').text) / h
        xmax = float(box.find('xmax').text) / w
        ymax = float(box.find('ymax').text) / h

        target = torch.tensor([xmin, ymin, xmax, ymax], dtype=torch.float32)

        # Training-time augmentation (before resize/normalize)
        if self.augment:
            # Random horizontal flip (update bbox to match)
            if random.random() < 0.5:
                image = TF.hflip(image)
                target = torch.tensor([1 - target[2], target[1], 1 - target[0], target[3]], dtype=torch.float32)
            # Random color jitter (no bbox change)
            if random.random() < 0.5:
                image = TF.adjust_brightness(image, random.uniform(0.8, 1.2))
            if random.random() < 0.5:
                image = TF.adjust_contrast(image, random.uniform(0.8, 1.2))
            if random.random() < 0.5:
                image = TF.adjust_saturation(image, random.uniform(0.8, 1.2))

        if self.transform:
            image = self.transform(image)
        return image, target

# --- 2. Model Architecture ---
class MobileNetDetector(nn.Module):
    def __init__(self):
        super().__init__()
        # Using pre-trained weights for transfer learning
        backbone = models.mobilenet_v3_large(weights='DEFAULT')
        self.features = backbone.features
        self.avgpool = nn.AdaptiveAvgPool2d(1)
        self.regressor = nn.Sequential(
            nn.Linear(960, 128),
            nn.ReLU(),
            nn.Linear(128, 4),
            nn.Sigmoid() # Sigmoid ensures output is between 0 and 1
        )

    def forward(self, x):
        x = self.features(x)
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        return self.regressor(x)

# --- 3. Utility Functions ---
def calculate_iou(preds, labels):
    x1, y1 = torch.max(preds[:, 0], labels[:, 0]), torch.max(preds[:, 1], labels[:, 1])
    x2, y2 = torch.min(preds[:, 2], labels[:, 2]), torch.min(preds[:, 3], labels[:, 3])
    intersection = (x2 - x1).clamp(0) * (y2 - y1).clamp(0)
    area_pred = (preds[:, 2] - preds[:, 0]) * (preds[:, 3] - preds[:, 1])
    area_gt = (labels[:, 2] - labels[:, 0]) * (labels[:, 3] - labels[:, 1])
    union = area_pred + area_gt - intersection + 1e-6
    return (intersection / union).mean()

def log_images_to_tb(writer, epoch, imgs, targets, preds, name="Val_Samples"):
    """Visualizes 4 images with Green (GT) and Red (Pred) boxes."""
    img_list = []
    num_to_log = min(4, imgs.shape[0])

    for i in range(num_to_log):
        # Denormalize image
        img = imgs[i].cpu().permute(1, 2, 0).numpy()
        img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]
        img = (img.clip(0, 1) * 255).astype('uint8').copy()
        h, w, _ = img.shape

        # Red Box: Predicted
        p = preds[i].cpu().numpy()
        cv2.rectangle(img, (int(p[0]*w), int(p[1]*h)), (int(p[2]*w), int(p[3]*h)), (255, 0, 0), 2)

        # Green Box: Ground Truth
        t = targets[i].cpu().numpy()
        cv2.rectangle(img, (int(t[0]*w), int(t[1]*h)), (int(t[2]*w), int(t[3]*h)), (0, 255, 0), 2)

        img_list.append(torch.from_numpy(img).permute(2, 0, 1))

    grid = vutils.make_grid(img_list)
    writer.add_image(name, grid, epoch)

# --- 4. Experiment Configurations ---
device = get_device()
print(f"Using device: {device}")
DATASET_PATH = './dog-2' # Update this to your folder name from Roboflow
EPOCHS = 60

# Train transform: augmentation + resize + normalize
train_transform = transforms.Compose([
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
# Val/test: no augmentation
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

configs = [
    {'name': 'LR_1e-3_BS_16', 'lr': 0.001, 'bs': 16},
    {'name': 'LR_1e-4_BS_16', 'lr': 0.0001, 'bs': 16},
    {'name': 'LR_5e-5_BS_16', 'lr': 0.00005, 'bs': 16},

    {'name': 'LR_1e-3_BS_32', 'lr': 0.001, 'bs': 32},
    {'name': 'LR_1e-4_BS_32', 'lr': 0.0001, 'bs': 32},
    {'name': 'LR_5e-5_BS_32', 'lr': 0.00005, 'bs': 32},

    {'name': 'LR_1e-3_BS_64', 'lr': 0.001, 'bs': 64},
    {'name': 'LR_1e-4_BS_64', 'lr': 0.0001, 'bs': 64},
    {'name': 'LR_5e-5_BS_64', 'lr': 0.00005, 'bs': 64}

]

SAVE_DIR = './dogs'
# Create the directory if it doesn't exist
os.makedirs(SAVE_DIR, exist_ok=True)
if os.path.exists(SAVE_DIR):
    print("Success: Folder found!")
    print("Files currently inside:", os.listdir(SAVE_DIR))
else:
    print("Error: Path not found. Check your Drive folder names.")

# Store best val IoU per config for final summary
config_results = []

# --- 5. Execution Loop ---
for cfg in configs:
    # Each config gets its own directory: SAVE_DIR/<config_name>/
    config_dir = os.path.join(SAVE_DIR, cfg['name'])
    os.makedirs(config_dir, exist_ok=True)

    print(f"\n>>> Starting Experiment: {cfg['name']} (outputs in {config_dir})")

    # FIX 1: Use cfg['bs'] instead of configs['bs']; train uses augmentation
    train_loader = DataLoader(
        Part2Dataset(DATASET_PATH, 'train', train_transform, augment=True),
        batch_size=cfg['bs'], shuffle=True
    )
    val_loader = DataLoader(Part2Dataset(DATASET_PATH, 'valid', transform),
                            batch_size=cfg['bs'])

    model = MobileNetDetector().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg['lr'])
    criterion = nn.SmoothL1Loss()

    # TensorBoard and checkpoints saved inside this config's directory
    writer = SummaryWriter(os.path.join(config_dir, 'runs'))

    best_val_loss = float('inf')
    best_val_iou = 0.0
    patience, counter = 8, 0

    for epoch in range(EPOCHS):
        # Training Phase
        model.train()
        train_loss, train_iou = 0, 0
        for imgs, targets in train_loader:
            imgs, targets = imgs.to(device), targets.to(device)
            optimizer.zero_grad()
            preds = model(imgs)
            loss = criterion(preds, targets)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
            train_iou += calculate_iou(preds, targets).item()

        avg_train_loss = train_loss / len(train_loader)
        avg_train_iou = train_iou / len(train_loader)

        # Validation Phase
        model.eval()
        val_loss, val_iou = 0, 0
        with torch.no_grad():
            for i, (imgs, targets) in enumerate(val_loader):
                imgs, targets = imgs.to(device), targets.to(device)
                preds = model(imgs)
                val_loss += criterion(preds, targets).item()
                val_iou += calculate_iou(preds, targets).item()

                # Log images
                if i == 0 and (epoch % 5 == 0 or epoch == EPOCHS-1):
                    log_images_to_tb(writer, epoch, imgs, targets, preds)

        avg_val_loss = val_loss / len(val_loader)
        avg_val_iou = val_iou / len(val_loader)

        # Track best val IoU for this config (for final summary)
        iou_improved = avg_val_iou > best_val_iou
        if iou_improved:
            best_val_iou = avg_val_iou

        # Logging
        writer.add_scalars('Loss', {'Train': avg_train_loss, 'Val': avg_val_loss}, epoch)
        writer.add_scalars('IoU', {'Train': avg_train_iou, 'Val': avg_val_iou}, epoch)

        print(f"Epoch {epoch+1}: Train IoU: {avg_train_iou:.4f}, Val IoU: {avg_val_iou:.4f}")

        # Saving & Early Stopping
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            save_path = os.path.join(config_dir, 'best_model.pth')
            torch.save(model.state_dict(), save_path)
            print(f"--> Saved best model (by loss) to {save_path}")
            counter = 0
        elif iou_improved:
            save_path = os.path.join(config_dir, 'best_model_iou.pth')
            torch.save(model.state_dict(), save_path)
            print(f"--> Saved best model (by IoU) to {save_path}")
            counter = 0
        else:
            counter += 1
            if counter >= patience:
                print(f"Early Stopping triggered at epoch {epoch+1}")
                break

    writer.close()
    config_results.append({'name': cfg['name'], 'best_val_iou': best_val_iou})

# --- Print summary: best val IoU per config ---
print("\n" + "=" * 60)
print("BEST VALIDATION IoU PER CONFIG")
print("=" * 60)
for r in config_results:
    print(f"  {r['name']}: {r['best_val_iou']:.4f}")
print("=" * 60)
best_overall = max(config_results, key=lambda x: x['best_val_iou'])
print(f"Best overall: {best_overall['name']} with Val IoU {best_overall['best_val_iou']:.4f}")
print("=" * 60)

import torch
import os

# --- 1. Setup Path and Model ---
# Load from a specific config's directory (e.g. LR_1e-3_BS_16/best_model.pth)
MODEL_PATH = './dogs/LR_1e-3_BS_16/best_model.pth'
device = get_device()

# Initialize architecture and load weights
model = MobileNetDetector().to(device)
model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
model.eval() # CRITICAL: Sets dropout/batchnorm to evaluation mode

# --- 2. Create Loaders for Evaluation ---
# We keep BATCH_SIZE small to avoid memory issues during heavy metrics calculation
eval_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

valid_loader = DataLoader(Part2Dataset(DATASET_PATH, 'valid', eval_transform), batch_size=16)
test_loader = DataLoader(Part2Dataset(DATASET_PATH, 'test', eval_transform), batch_size=16)


import matplotlib.pyplot as plt
import matplotlib.patches as patches

def plot_test_predictions(model, loader, device, num_images=16):
    model.eval()
    # Get one batch of data from the test set
    images, targets = next(iter(loader))
    images, targets = images.to(device), targets.to(device)

    with torch.no_grad():
        predictions = model(images)

    # Setup the plot grid
    rows = 4
    plt.figure(figsize=(18, 6 * rows))

    for i in range(num_images):
        # 1. Denormalize the image for display
        img = images[i].cpu().permute(1, 2, 0).numpy()
        # MobileNet normalization values
        img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]
        img = img.clip(0, 1)

        plt.subplot(rows, 4, i + 1)
        plt.imshow(img)

        # 2. Get coordinates (scaling 0-1 back to 224 pixels)
        pred_box = predictions[i].cpu().numpy() * 224
        gt_box = targets[i].cpu().numpy() * 224

        # 3. Create Rectangles
        # patches.Rectangle uses (x, y, width, height)
        rect_pred = patches.Rectangle((pred_box[0], pred_box[1]),
                                     pred_box[2] - pred_box[0],
                                     pred_box[3] - pred_box[1],
                                     linewidth=3, edgecolor='red', facecolor='none', label='Pred')

        rect_gt = patches.Rectangle((gt_box[0], gt_box[1]),
                                   gt_box[2] - gt_box[0],
                                   gt_box[3] - gt_box[1],
                                   linewidth=2, edgecolor='lime', facecolor='none', linestyle='--', label='GT')

        # 4. Add patches to the axes
        ax = plt.gca()
        ax.add_patch(rect_pred)
        ax.add_patch(rect_gt)

        # 5. Calculate individual IoU for the title
        iou_score = calculate_iou(predictions[i:i+1], targets[i:i+1]).item()
        plt.title(f"Test Image {i+1} | IoU: {iou_score:.2f}")
        plt.axis('off')

    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

# --- Run the Visualization ---
plot_test_predictions(model, test_loader, device)

import cv2
import torch
from torchvision import transforms
from PIL import Image
import numpy as np
